# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: message.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rmessage.proto\"\x0b\n\tWorldData\"W\n\x07Point3D\x12\t\n\x01x\x18\x01 \x01(\x02\x12\t\n\x01y\x18\x02 \x01(\x02\x12\t\n\x01z\x18\x03 \x01(\x02\x12\r\n\x05rot_x\x18\x04 \x01(\x02\x12\r\n\x05rot_y\x18\x05 \x01(\x02\x12\r\n\x05rot_z\x18\x06 \x01(\x02\"J\n\x0b\x43\x61meraFrame\x12\x0e\n\x06height\x18\x01 \x01(\x05\x12\r\n\x05width\x18\x02 \x01(\x05\x12\x0e\n\x06\x66ormat\x18\x03 \x01(\t\x12\x0c\n\x04\x64\x61ta\x18\x04 \x01(\x0c\"+\n\x0c\x43\x61meraFrames\x12\x1b\n\x05\x66rame\x18\x01 \x03(\x0b\x32\x0c.CameraFrame\"*\n\x16ParkingSensorDistances\x12\x10\n\x08\x64istance\x18\x01 \x03(\x02\"#\n\x08Points3D\x12\x17\n\x05point\x18\x01 \x03(\x0b\x32\x08.Point3D\"\xf2\x02\n\tAgentData\x12\x12\n\nis_crashed\x18\x01 \x01(\x08\x12\x10\n\x08steering\x18\x02 \x01(\x02\x12\r\n\x05speed\x18\x03 \x01(\x02\x12\x18\n\x05lidar\x18\x04 \x03(\x0b\x32\t.Points3D\x12(\n\x07\x63\x61meras\x18\x05 \x03(\x0b\x32\x17.AgentData.CamerasEntry\x12\x37\n\x0fparking_sensors\x18\x06 \x03(\x0b\x32\x1e.AgentData.ParkingSensorsEntry\x12$\n\x12global_coordinates\x18\x07 \x01(\x0b\x32\x08.Point3D\x1a=\n\x0c\x43\x61merasEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\x1c\n\x05value\x18\x02 \x01(\x0b\x32\r.CameraFrames:\x02\x38\x01\x1aN\n\x13ParkingSensorsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12&\n\x05value\x18\x02 \x01(\x0b\x32\x17.ParkingSensorDistances:\x02\x38\x01\"I\n\x07Message\x12\x1e\n\nagent_data\x18\x01 \x01(\x0b\x32\n.AgentData\x12\x1e\n\nworld_data\x18\x02 \x01(\x0b\x32\n.WorldDatab\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'message_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _AGENTDATA_CAMERASENTRY._options = None
  _AGENTDATA_CAMERASENTRY._serialized_options = b'8\001'
  _AGENTDATA_PARKINGSENSORSENTRY._options = None
  _AGENTDATA_PARKINGSENSORSENTRY._serialized_options = b'8\001'
  _globals['_WORLDDATA']._serialized_start=17
  _globals['_WORLDDATA']._serialized_end=28
  _globals['_POINT3D']._serialized_start=30
  _globals['_POINT3D']._serialized_end=117
  _globals['_CAMERAFRAME']._serialized_start=119
  _globals['_CAMERAFRAME']._serialized_end=193
  _globals['_CAMERAFRAMES']._serialized_start=195
  _globals['_CAMERAFRAMES']._serialized_end=238
  _globals['_PARKINGSENSORDISTANCES']._serialized_start=240
  _globals['_PARKINGSENSORDISTANCES']._serialized_end=282
  _globals['_POINTS3D']._serialized_start=284
  _globals['_POINTS3D']._serialized_end=319
  _globals['_AGENTDATA']._serialized_start=322
  _globals['_AGENTDATA']._serialized_end=692
  _globals['_AGENTDATA_CAMERASENTRY']._serialized_start=551
  _globals['_AGENTDATA_CAMERASENTRY']._serialized_end=612
  _globals['_AGENTDATA_PARKINGSENSORSENTRY']._serialized_start=614
  _globals['_AGENTDATA_PARKINGSENSORSENTRY']._serialized_end=692
  _globals['_MESSAGE']._serialized_start=694
  _globals['_MESSAGE']._serialized_end=767
# @@protoc_insertion_point(module_scope)
